lib/sqlitex.ex
test/sqlitex_test.exs

Hi, considering #2 I added third argument `opts` to `Sqlitex.query`.
The point is that users can specify the data structure of return values.
This change allows us to do:
```elixir
Sqlite.query(db, sql)            #=> [[id: 1, name: ...], [id: 2, name: ...]]
Sqlite.query(db, sql, into: [])  #=> [[id: 1, name: ...], [id: 2, name: ...]] (same as above)
Sqlite.query(db, sql, into: %{}) #=> [%{id: 1, name: ...}, %{id: 2, name: ...}]
```
The test is also added.
Thank you.

Proposal: accept `into` option

---

lib/sqlitex/server.ex
test/sqlitex_test.exs

These changes:
1. Move `Sqlitex.close/1` into `Sqlitex.Server.terminate/2` so that the database connection gets closed regardless of the way the GenServer is terminated.
2. Move `Sqlitex.open/1` into `Sqlitex.Server.init/1` to provide some symmetry to (1) above.
3. Convert `Sqlitex.Server.stop/1` to a cast since we no longer expect a return value from close.
I made the first change because the Ecto tests were killing the GenServer process, and since I wasn't able to call stop() explicitly, the SQLite connection was never closed.  The other changes just seemed like a natural consequence of the first.

GenServer improvements

---

README.md
lib/sqlitex/server.ex
test/sqlitex_test.exs

This request adds GenServer options to `Sqlitex.Server` so that it can be used as a worker.  I also updated the README to reflect the API changes.

Adds GenServer Options to Sqlitex.Server

---

lib/sqlitex/row.ex
test/sqlitex_test.exs

Converts all column types to lowercase strings so that no matter what the upcase/downcase distribution of letters, the types will be interpreted correctly.
@mmmries:  I noticed you have given me write access to the repo, and I could commit it myself.  I'll leave it open for a couple of days to give you a chance to review it if you'd like.
Thanks!

Fix for Issue #15

---

.travis.yml
lib/sqlitex.ex
lib/sqlitex/query.ex
lib/sqlitex/row.ex
mix.exs
mix.lock
test/sqlitex_test.exs

There are quite a few changes in this patch, but they all addresses only two major issues:
1. Errors from `:esqlite3.prepare/2` and `:esqlite3.bind/2` are now passed to the calling function instead of throwing match errors.
2. Conversions to and from Elixir/Erlang types and SQLite values.
See the new test cases for usage.  Let me know what you think.
(One thing to note is the conversion from datetime tuples of the form `{{year, month, day}, {hour, min, sec, usecs}}` to strings.  We already handled the Erlang datetime tuple, but the Ecto code likes to make use of one with microseconds.  I don't know if this type of tuple is used anywhere else in the Elixir/Erlang world.  If it seems too Ecto specific, then I can put it in the Sqlite.Ecto code instead.  To keep these datetime types …

Fix bugs found by Ecto integration tests

---

lib/sqlitex/server.ex
test/sqlitex_test.exs

New Ecto 0.12 integration tests to be passed :)
I added timeout option checking to `Sqlitex.Server.exec/3` and `query/3`.  I did not add the check to `Sqlitex.Server.create_table/4` because the current `table_opts` is the third of four arguments and is already optional.  We could move the table options to the end of the call like we do for the exec and query functions.
Ultimately, I decided to just ignore `create_table` for now.  I'll opt to revisit it later.

Passes timeout option to GenServer.call/3

---

lib/sqlitex/query.ex
mix.exs
mix.lock

resolves #21
Bumps the dependency to on esqlite to `0.2.0`
Removes the workaround for `{:error, :no_columns}`. We still need the `case` statements because we need to capture the types/names and merge them into the `Sqlitex.Query` struct, so this doesn't end making a huge difference, but it is nice to remove two cases.
Did I miss any tests that should be removed. I didn't see any that were specific to the `no_columns` workaround. i think all the tests cases could still be valuable.
/cc @jazzyb

Remove no column workaround

---

lib/sqlitex.ex
lib/sqlitex/errors.ex
lib/sqlitex/query.ex
lib/sqlitex/statement.ex
test/sqlitex_test.exs
test/statement_test.exs

I've got an application using Sqlitex that's going to be running for a fairly long time and only ever makes a couple of queries.  When I've been using sqlite in other languages, I'd usually just create a prepared statement once and re-use it multiple times.  This doesn't seem to be something that the Sqlitex API supported, so I've re-arranged things a bit so that it does.
* Created a `Sqlitex.Statement` module.  Most of the code from `Sqlitex.Query` has been moved into this module, though I've made a lot of the functions public when they were private before.
* The `pipe_matching` functionality you were using is pretty cool, though I've modified it slightly - using `pipe_with` to extract the value from the `:ok` tuple before passing it in to the next function.  Makes the interface of the …

Allow re-use of prepared statements

---

lib/sqlitex/query.ex
lib/sqlitex/statement.ex
test/statement_test.exs

`fetch_all!` was incorrectly assuming that `fetch_all` returns `{:ok, results}` - actually it just returns `results`.

Fix `Sqlitex.Statement.fetch_all!`

---

lib/sqlitex/row.ex
test/row_test.exs
test/sqlitex_test.exs

It turns out that most of sqlite's [date and time functions](https://www.sqlite.org/lang_datefunc.html) us a format without any fractional seconds.
This commit adds support for querying those values out of the database.
Resolves #27 
@Tica2 this adds support for a datetime string with no fractional seconds, but doesn't handle the case where the string is saved with 3 decimal points (milliseconds), or just a single decimal point (tenths of a second).
Since sqlite is actually just storing this as a string I wonder how far we should go in supporting the different formats. Any ideas @jazzyb or @obmarg?

Support for datetime values without fractional seconds

---

config/config.exs
config/dev.exs
config/test.exs
mix.lock

This updates Dogma to work with elixir `1.1.0` and defines our own RuleSet. Currently we can't configure the line length without just re-defining our own ruleset. The Dogma team is currently working on this: https://github.com/lpil/dogma/issues/70
So in the meantime I just copied and pasted the `Dogma.RuleSet.All` and changed the line length configuration to 100 chars per line.
Ignoring the `test_database.exs` file and set max line length to 100 chars reduces our errors from 289 down to 44 errors.

Dogma fixes

---

mix.exs

This makes building releases of applications using exrm easier - without
this exrm doesn't realise that it needs to package up esqlite into the
release.  This is documented under the first bullet point here:
https://hexdocs.pm/exrm/extra-common-issues.html
It's easily solved by adding `:esqlite` to the application you're
building, but it'd be nice not to have to do that.

Add esqlite to applications in mix.exs

---

.gitignore
.travis.yml
lib/sqlitex/statement.ex
mix.lock

Fixes #39
Also updates the erlang/elixir versions that we run on travis and ignores the mix.lock from the git repo.
/cc @jazzyb @obmarg

Fix doctests

---

.travis.yml
test/row_test.exs

I've added a new unit test to `row_test.exs` which explores an issue I've seen trying to bring [sqlite_ecto](https://github.com/jazzyb/sqlite_ecto) up to speed on current Elixir, OTP, and eventually Ecto.
As shown in https://travis-ci.org/scouten/sqlitex/builds/186397549, which targets the branch from this PR, the OTP 18 builds succeed, but the OTP 19 builds fail. FWIW if I run this on my Mac using OTP 19, it succeeds.
I suspect this might be indicative of a larger OTP 19 issue, but wanted to bring this to your attention ASAP.

Row.from fails to parse decimal data types in some cases.

---

.travis.yml
lib/sqlitex/query.ex
lib/sqlitex/sql_builder.ex
mix.exs
test/order_test.exs
test/sum_test.exs

With the release of Elixir 1.4 this project shows several compile-time warnings. This PR removes these warnings:
* bare-words that resolve to function calls are now deprecated
* fixed this in `mix.exs` and in the excheck tests for summing and ordering in queries
* Dict is deprecated so I've replaced it will calls to `Map.get/3` and `Keyword.get/3`
* I think this shouldn't cause any problem because we have documented the expected types that get passed into `Query.query` and `Query.query_rows` as keyword lists. In `SqlBuilder` we use `Enum.into` to create a map, so we just need to use `Map.get/3`
If anyone has a few minutes to review this and make sure I'm not breaking any interfaces that would be very helpful.
/cc @jazzyb @obmarg @scouten

Elixir 1.4

---

lib/sqlitex/statement.ex
test/statement_test.exs

Ecto often requires the ability to return auto-generated values from INSERT and UPDATE statements (consider row IDs for newly-inserted content as an example). This isn't directly supported by SQLite (unlike, for example, Postgres), but can be implemented by adding temporary triggers.
In Ecto 1.x (and corresponding jazzyb/sqlite_ecto), the access to SQLite was synchronous so the SQLite Ecto adapter could add and remove the triggers as it needed.
In Ecto 2.x (and scouten/sqlite_ecto2 that is nearing its initial release), we now use Sqlitex.Server so adding and removing temporary triggers is not feasible from external code because (rightly so) the Sqlitex.Server code is self-contained.
This patch ports the returning clause support from jazzyb/sqlite_ecto into Sqlitex.Server.

Implement returning clause support.

---

mix.exs

Without this change, sqlitex can not be by a Hex package that also uses Ecto 2.1.4.
```
sqlite_ecto2 scouten$ mix hex.publish
** (Mix) Can't build package with overridden dependency decimal, remove `override: true`
sqlite_ecto2 scouten$ mix deps.unlock decimal
sqlite_ecto2 scouten$ mix deps.get
Running dependency resolution...
Failed to use "decimal" (versions 1.1.0 to 1.1.2) because
ecto (version 2.1.4) requires ~> 1.2
postgrex (version 0.13.0) requires ~> 1.0
sqlitex (version 1.3.0) requires ~> 1.1.0
mix.exs specifies ~> 1.1
Failed to use "decimal" (versions 1.2.0 to 1.3.1) because
sqlitex (version 1.3.0) requires ~> 1.1.0
mix.exs specifies ~> 1.1
** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or …
```

Relax requirement on :decimal library.

---

.travis.yml
lib/sqlitex.ex
lib/sqlitex/query.ex
lib/sqlitex/row.ex

These changes quiet the warnings emitted when compiling under Elixir
1.5.1, they also work under 1.4.4.
This addresses my issue https://github.com/mmmries/sqlitex/issues/60
but I'm not sure if it's the "right thing" to do. That depends on how much
testing you want to do with older Elixirs.

Get rid of warnings when compiling under 1.5.x #60

---

config/config.exs
lib/sqlitex.ex
lib/sqlitex/query.ex
lib/sqlitex/statement.ex
mix.exs

I was doing some experiments with `dialyxir` and found that the dependencies in this project (dev dependencies) were a bit out of date, and that we had some typespec errors.
Some of these dialyzer warnings were form [incorrect type specs in esqlite](https://github.com/mmzeeman/esqlite/pull/37). But some of them were just our own mistakes. Building against my branch of esqlite is now clean of errors.

Deps and typespecs

---

.travis.yml

This is just an update to run out Travis builds against the recent version of Elixir and OTP.

run Travis builds on recent OTP and Elixir Releases

---

lib/sqlitex.ex
lib/sqlitex/config.ex
lib/sqlitex/query.ex
lib/sqlitex/server.ex
lib/sqlitex/server/statement_cache.ex
lib/sqlitex/statement.ex
test/server/statement_cache_test.exs

Hello.
First, thank you for the library. It's come in very useful for us.
We've been doing some work where we needed to increase the timeout `esqlite` applies to various operations. This pull request updates Sqlitex to expose the timeout argument in the various places that `esqlite` does so.
With these changes, Sqlitex defaults to the `esqlite` timeout of 5000 ms, and uses a combination of default values on the function arguments and implementing an `Application`-level config to leave the interface of Sqlitex unchanged for those who don't need to modify the timeout.
I think this is a broadly useful enough change to consider bringing into the upstream, but I worry that the implementation is a little noisy. Please let me know any changes you want made.
Thanks again.

Allow esqlite’s timeout to be specified

---

.travis.yml
lib/sqlitex/row.ex
lib/sqlitex/server/statement_cache.ex
mix.exs
test/sqlitex_test.exs

I noticed the other day that we had a couple of dialyzer errors in the project. I would like to minimize these in the future so I thought that running dialyzer during CI would be nice. In order to make this run relatively quickly I've added caching of the `/home/travis/.mix` directory which means that Travis should cache the PLT file for erlang/elixir libraries and then we just re-build the PLTs for our deps and our project on each build.
__Dialyzer Errors__
The first error was that when calling `esqlite3.q/2` we were passing the query as a binary, but the function was spec'd as expecting an `iolist()`. I actually [fixed this](https://github.com/mmzeeman/esqlite/pull/37) in esqlite a long time ago, but it looks like that change was missed in the `0.2.3` release. So I pulled the master …

Fix dialyzer errors

---

lib/sqlitex/row.ex
test/sqlitex_test.exs

I created table `price_list` with field `price DECIMAL(34, 10)`. And when I try to select data from this table, I get error. Then I create same table and field without space between precision and scale -  query working.
```
** (exit) exited in: GenServer.call(Sqlitex.Server, {:query, "select * from price_list ORDER BY company_id limit 1", []}, 5000)
** (EXIT) an exception was raised:
** (ArgumentError) argument error
:erlang.binary_to_integer(" 10")
(elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
(elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
(sqlitex) lib/sqlitex/row.ex:58: Sqlitex.Row.translate_value/1
(elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
(elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
(sqlitex) lib/sqlitex/row.ex:16: …
```

fix decimal scale and precision parsing

---

README.md
lib/sqlitex.ex
lib/sqlitex/query.ex
lib/sqlitex/server.ex
lib/sqlitex/server/statement_cache.ex
lib/sqlitex/statement.ex

SQLite was spelling inconsistently in the README.md and comments (sometimes `sqlite`, sometimes `SQLite`). Normalized on the capitalized version.
Additionally, there were some run-on sentences, which were broken apart with commas. Also, added line breaks between functions where needed.

Consistent SQLite spelling, grammar fixes, line breaks.

---

.circleci/config.yml
mix.exs

This is an attempt to improve our CI checks. In our `mix.exs` file we support elixir `~> 1.4`, but we currently only run our CI checks against `1.8.1`. This would change out Circle config to build and run tests on each of `1.4.5`, `1.5.3`, `1.6.6`, `1.7.4` and `1.8.1` (the latest patch for each minor version since 1.4) and also run a single job that runs credo checks, dialyzer checks, formatting checks and code coverage checks.

run tests for multiple elixir versions and add dialyzer checks

---

lib/sqlitex.ex
lib/sqlitex/query.ex

When doing something as simple as:
```elixir
case Sqlitex.query!(conn, "pragma #{clause};") do
[[{^key, value}]] ->
single_value(key, value)
values when is_list(values) ->
multiple_values(key, values)
end
```
...I get this Dialyzer error:
```plain
lib/yourapp/yourapp.ex:100:pattern_match
The pattern can never match the type.
Pattern:
[[{_, _value}]]
Type:
[[]]
```
Upon inspecting Sqlitex's code, I noticed that the `query` / `query!` functions have two specs each (to cover for the default and non-default parameters) but where a list of zero or more keyword lists is expected to be returned, the spec says the function should return `[[]]`.
This PR modifies the `[[]]` specs to the more accurate `[keyword]`.

Fix typespecs that refer to list of keywords but are instead coded as an empty list containing another empty list

---

lib/sqlitex/row.ex

I realized that my datetime fields sometimes come back with just the date, and then this match crashes. So here a fix.

Fixed date case match

---

lib/sqlitex.ex
lib/sqlitex/server.ex
test/server_test.exs
test/sqlitex_test.exs

On the original pull request there is unfortunately not much traction. But here is the grown version that I'm using in the mean time since. It has a couple of improvements on top of the initial with_transaction pull request.
- Server.with_transaction() becomes reentrancy safe. Instead of passing a pure Sqlitex db instance, it is passing it's own pid as parameters, and it's safe to call all Server.* methods on it without getting stuck in a GenServer self-call
- This allows **faster** query() within with_transaction() calls because the StatementCache of the Sqlitex.Server instance is now used.  
```
BEFORE
iex> Sqlitex.Server.with_transaction(server, fn(db) ->
...>   Sqlitex.exec(db, "create table foo(id integer)")
...>   Sqlitex.exec(db, "insert into foo (id) values(42)")
...> end)
NOW …
```

with_transaction #2

---

lib/sqlitex/server.ex

The helper that takes an atom converts that into a pid, but in the case that a `Process.whereis(bla)` returns `nil` this unfortunately did lead to an endless loop. I've added a `nil` case now that fixes this loop.

Fixed endless loop when process not found
